name: backend

on:
  push:
    paths:
      - .github/workflows/backend.yml
      - backend/**
  workflow_dispatch:
    inputs:
      command:
        description: Build only or deploy
        type: choice
        required: true
        options:
          - build-only
          - build-and-deploy

jobs:
  backend:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: build
        run: |
          docker buildx build \
            --output "${RUNNER_TEMP}" \
            backend/Chenfeng.Twsd.Api

      - if: github.ref == 'refs/heads/main' && inputs.command != 'build-only'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::340554939768:role/app-deployer

      - name: deploy
        if: github.ref == 'refs/heads/main' && inputs.command != 'build-only'
        working-directory: ${{ runner.temp }}
        run: |
          zip package.zip bootstrap
          aws lambda update-function-code \
            --function-name twsd-api \
            --zip-file "fileb://${RUNNER_TEMP}/package.zip"
