name: ui

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/ui.yml
      - ui/**
  workflow_dispatch:

jobs:
  backend:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::340554939768:role/app-deployer

      - name: deploy
        working-directory: ui
        run: aws s3 sync . s3://twsd/ --delete
